adds stewardship blog post
datatogether/website pull request #82
Opened 2019-10-31 22:55 UTC by Frijol

Hello @lightandluck @b5 @RangerMauve @Mr0grog @ericnost ! Here (at last) is a draft blog post from our **Stewardship** conversation. Please have a look!

In particular, **please**:
1. Add yourself as an author if you would like to be acknowledged as an author (after all, you're the source material)
2. Double check that the things I *said* you said actually sound like something you would say. As usual, I did some pretty severe editing to shorten and improve coherence, so it's possible I've totally misconstrued your meaning
3. In light of the above, another option is to have your name changed to an alias if you would prefer.

Timeline for publication:
* [ ] By 11/7 please make any comments/edits
* [ ] By 11/14 I will merge/post!

2019-11-04 22:57 UTC, lightandluck requested changes
Mainly replaced links to the video with a link to transcript instead because the video was deleted =(

2019-11-04 22:57 UTC, lightandluck commented on content/posts/04_stewardship.md
> +This month's reading selections begin with traditional notions and practices of stewardship: Pastor Henry Wright's sermon [The Stewardship of Time](https://youtu.be/RWCbK8qRkuo?t=170); selections fro
The video for the sermon was removed =(
Suggest we link to transcript instead
(Really wish I had downloaded the audio, darn)

```suggestion
This month's reading selections begin with traditional notions and practices of stewardship: Pastor Henry Wright's sermon [The Stewardship of Time](https://docs.google.com/document/d/1l8tfRlAAL6y4JDRpeK4s--NTRcdBitMHpjsVfAzbPtU/edit); selections from [Haa Tuwunáagu Yís](https://www.goodreads.com/book/show/2146282.Haa_Tuwun_agu_Y_s_for_Healing_Our_Spirit), a collection of Tlingit narratives compiled by Nora Marks Dauenhauer; and [Tending the Wild](https://www.ucpress.edu/book.php?isbn=9780520280434) by Kat Anderson, a view into Ohlone land stewardship practices.
```

2019-11-04 22:57 UTC, lightandluck commented on content/posts/04_stewardship.md
> +authors: ["Kelsey Breseman", "Data Together"]
```suggestion
authors: ["Kelsey Breseman", "Kevin Nguyen", "Data Together"]
```

2019-11-04 22:57 UTC, lightandluck commented on content/posts/04_stewardship.md
> +*From the [Wright sermon](https://youtu.be/RWCbK8qRkuo?t=170):*
```suggestion
*From the [Wright sermon](https://docs.google.com/document/d/1l8tfRlAAL6y4JDRpeK4s--NTRcdBitMHpjsVfAzbPtU/edit):*
```

2019-11-04 22:57 UTC, lightandluck commented on content/posts/04_stewardship.md
> +**KEVIN**: I liked that people touched on ownership. I was chatting with my neighbor, who is an Episcopelian pastor. They had a great term, that it's the "antidote to dominion". **Instead of lording
```suggestion
**KEVIN**: I liked that people touched on ownership. I was chatting with my neighbor, who is an Episcopalian pastor. They had a great term, that it's the "antidote to dominion". **Instead of lording over or controlling things, a steward is involved with the proper care and *use* of things.**
```

2019-11-04 22:57 UTC, lightandluck commented on content/posts/04_stewardship.md
> +**KEVIN**: That's a great way to leave us thinking. I hope people think about how to continue this conversation: defining how to be good stewards, and deciding what should be preserved, what we want
```suggestion
**KEVIN**: That's a great way to not end the conversation, but leave us thinking. I hope people think about how to continue this conversation: defining how to be good stewards, and deciding what should be preserved, what we want to preserve, or letting people choose. Thanks for an awesome conversation.
```

2019-11-04 22:57 UTC, lightandluck commented on content/posts/04_stewardship.md
> +1. Pastor Henry Wright, [The Stewardship of Time](https://youtu.be/RWCbK8qRkuo?t=170), 2019: 2:50-6:17. [Transcript](https://docs.google.com/document/d/1l8tfRlAAL6y4JDRpeK4s--NTRcdBitMHpjsVfAzbPtU/ed
```suggestion
1. Pastor Henry Wright, The Stewardship of Time, 2019: 2:50-6:17. [Transcript](https://docs.google.com/document/d/1l8tfRlAAL6y4JDRpeK4s--NTRcdBitMHpjsVfAzbPtU/edit)
```

2019-11-07 17:34 UTC, Frijol commented on content/posts/04_stewardship.md
> +This month's reading selections begin with traditional notions and practices of stewardship: Pastor Henry Wright's sermon [The Stewardship of Time](https://youtu.be/RWCbK8qRkuo?t=170); selections fro
Oh no! Thanks for checking the link though.

2019-11-07 17:37 UTC, Frijol commented
Thanks @lightandluck !

2019-11-07 19:00 UTC, lightandluck approved these changes

2019-11-14 18:01 UTC, merged